version: '3'
services:
  mongodb2:
    image: mongo:latest
    container_name: mongodb2
    ports:
      - "27017:27017"
    deploy:
      resources:
        limits:
          cpus: '0.75'  # 0.75 CPUs
          memory: 1G   # 1GB memory

  spring-app:
    image: test/rest
    depends_on:
      - mongodb2
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          cpus: '0.75'  # 0.75 CPUs
          memory: 1G   # 1GB memory